### PR TITLE
Use authSource from DSN

### LINKED ISSUE #23: Bulk write failed due to previous MongoDB\\Driver\\Exception\\AuthenticationException: Authentication failed
What is the proper format for `messenger.yaml`?

**Stack Trace**

```php
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "BulkWriteException",
  "hydra:description": "Bulk write failed due to previous MongoDB\\Driver\\Exception\\AuthenticationException: Authentication failed.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Operation/InsertOne.php",
      "line": 134,
      "args": []
    },
    {
      "namespace": "MongoDB\\Driver",
      "short_class": "Server",
      "class": "MongoDB\\Driver\\Server",
      "type": "->",
      "function": "executeBulkWrite",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Operation/InsertOne.php",
      "line": 134,
      "args": [
        [
          "string",
          "itcollect.messenger"
        ],
        [
          "object",
          "MongoDB\\Driver\\BulkWrite"
        ],
        [
          "array",
          []
        ]
      ]
    },
    {
      "namespace": "MongoDB\\Operation",
      "short_class": "InsertOne",
      "class": "MongoDB\\Operation\\InsertOne",
      "type": "->",
      "function": "execute",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Collection.php",
      "line": 931,
      "args": [
        [
          "object",
          "MongoDB\\Driver\\Server"
        ]
      ]
    },
    {
      "namespace": "MongoDB",
      "short_class": "Collection",
      "class": "MongoDB\\Collection",
      "type": "->",
      "function": "insertOne",
      "file": "/var/www/cpic/vendor/kcs/messenger-extra/lib/Transport/Mongo/MongoSender.php",
      "line": 103,
```

YAML:

```yaml
# messenger.yaml

framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            mongo: 'mongodb://root:root@192.168.64.100:27017/mydbname?authSource=mydbname'

        routing:
            'App\Message\RebaseLineAuditMessage': mongo
```

### PR DESCRIPTION
**Pull request by cnizzardini**
Set authSource from DSN, otherwise default to default database.

Resolves #23

### CODE REVIEW

**Comment by cnizzardini** [comment]
I don't care if you use this PR specifically, but this functions on my system for my needs. You can see what was happening and how this resolves it by looking at the logs in the issue.

I do require a fix and rather not run your library as a fork.

**Comment by alekitto** [comment]
Could you please try the `master` branch version and report if it is working or not?

In the meantime I suggest you to keep calm and be a little more polite the next time you report an issue or open a PR.
Please do not forget that the software you are using from the open-source world is developed in the vast majority of cases in the library authors' spare/free time. They are not paid for that time and they are not required to answer or support anyone in any case.

**Comment by cnizzardini** [comment]
I only meant that in case you didn't like my style of programming and you rather do your own PR. My apologies if it came off as demanding. It was more meant to accommodate your coding style.

**Comment by cnizzardini** [comment]
@alekitto dev-master works. closing this.

**Pull request closed without merging**
